remote_theme: "mmistakes/minimal-mistakes@4.19.2" 
title: Miguel-Angel Sicilia
github_username: msicilia

include: ["_pages"]

defaults:
  # _posts
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true




footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/msicilia"
 

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache