remote_theme: "mmistakes/minimal-mistakes@4.19.2" 
title: Miguel-Angel Sicilia
subtitle: homepage
title_separator: "-"
github_username: msicilia
minimal_mistakes_skin:   "air" # "default" "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

include:
  - _pages


author:
  name     : "Miguel-Angel Sicilia"
  avatar   : "/assets/images/gunter.jpg"
  bio      : "Computer Scientist"
  location : "Madrid, Spain"
  github   : "msicilia"
  linkedin:  "msicilia" 

defaults:
  # _posts
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true



# Plugins (previously gems:)
plugins:
        - jekyll-include-cache